### PR TITLE
CRUD actions for relationships

### PR DESCRIPTION
**Pull request by fquffio**
This PR implements CRUD actions for relationships, as of #926.

### CODE REVIEW

**Comment by fquffio** [comment]
In order to avoid making things too much simple for @batopa, this PR now also includes features as of #954. 😄

**Comment by batopa** [comment]
POST and PATCH don't check the `type` data, so I can do

``` http
POST /roles/1/relationships/users
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": [
        { "type": "gustavo", "id": "4" }
      ]
}
```

and the relationship between role with id=1 and user with id=4 is created.

**Comment by batopa** [comment]
The command pattern "actions" that save data on db should be handled inside a transaction because if some exception is triggered the data on db are corrupted.

For example, if exists a relationships between roles 1 and users 4 making a request like

``` http
POST /roles/1/relationships/users
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": [
        { "type": "users", "id": "4" }
      ]
}
```

and an exception is thrown in `\BEdita\Core\Model\Action\AddAssociated::__invoke()` between

``` php
$this->Association->unlink($entity, $relatedEntities);
```

and 

``` php
return $this->Association->link($entity, $relatedEntities);
```

(or fails the `link()` method) the association is removed from db.

Maybe it is enough put in transaction

``` php
// BEdita\API\Controller\ResourcesController::relationships()

if (!$action($id)) {
        throw new InternalErrorException(__('Could not update relationship "{0}"', $relationship));
}
```

**Comment by fquffio** [comment]
@batopa You're right. As far as I can see, the only non-transactional behavior is in `AddAssociated`, right?

**Comment by batopa** [comment]
@fquffio yes it seems to me too

**Comment by batopa** [comment]
`POST`, `PATCH` and `DELETE` requests don't always respond with status code compliant with JSON API specifications http://jsonapi.org/format/#crud-updating-relationship-responses

**Comment by fquffio** [comment]
@batopa Both issues should have been addressed by now.

**Comment by batopa** [comment]
- [x] https://github.com/bedita/bedita/pull/952#issuecomment-243496276 seems not resolved.
- [x] Trying to delete relationships via `PATCH`
  
  ``` http
  PATCH /roles/1/relationships/users
  
  {
     "data": []
  }
  ```
  
  respond with 500 status code with message "Invalid JSON" instead of delete all relationships. If we don't want implement this condition the response should be a `403 Forbidden`.
- [x] Trying to save relationships with repetition respond as `400` with message "Record Not Found"
  
  ``` http
  POST /roles/1/relationships/users
  
  {
      "data": [
          { "type": "users", "id": "2" },
          { "type": "users", "id": "2" }
      ]
  }
  ```
  
  maybe missing an `array_unique` on request data?
- [x] getting relationships of not existing role return a 200 with empty data instead of `404` as from [specification](http://jsonapi.org/format/#fetching-relationships-responses-404) (see the "Note")

**Comment by fquffio** [comment]
For what concerns https://github.com/bedita/bedita/pull/952#issuecomment-243496276, is `409 Conflict` fine? I can see no specific instructions in JSON API spec…

**Comment by batopa** [comment]
`409 Conflict` is correct, I found

> A server MUST return 409 Conflict when processing a POST request in which the resource object’s type is not among the type(s) that constitute the collection represented by the endpoint.
> 
> A server SHOULD include error details and provide enough information to recognize the source of the conflict.

**Pull request merged**
