### PR TITLE
#1207 feat: reduce jwt access token

### PR DESCRIPTION
**Pull request by didoda**
This implements #1207

### CODE REVIEW

**Comment by fquffio** [comment]
I'm not sure that we want this to be configurable… JWT content is mostly used for internal purposes, so I'd rather go with a hardcoded list of fields… :/

**Comment by didoda** [comment]
In #1207 @batopa commented: "Maybe we could define a default and make it configurable."
@fquffio suggests no config (easy to achieve, with trivial change in code).
If a specific config is not necessary now, I'd rather get rid of it and think about it in future (when needed).

**Comment by fquffio** [comment]
Ok, I didn't read @batopa 's comment. I don't know… Is it necessary to make it configurable? I'd prefer avoid adding configuration keys until we actually need 'em — the more configuration keys we add now, the more likely it is to forget about them and re-invent the wheel somewhen in the future. 🙃

**Review by stefanorosanelli — APPROVED** [review]

**Comment by batopa** [comment]
@fquffio in some situations the username could be considered a sensitive information, for example if it's an email, so I would avoid to store it in JWT. But as you said we can think about it later.

**Pull request merged**
