### PR TITLE
Passwd policy

### PR DESCRIPTION
**Pull request by stefanorosanelli**
This PR implements first part of #1428 

Simple password format validation rule was added via new `Auth` key config,

### CODE REVIEW

**Comment by batopa** [comment]
Just an observation:

I would prefer something as
```
'Auth' => [
     'passwordPolicy' => [
          'rule' => // anonymous function or class name to use for validation or regexp...,
           'message' => '',
     ]
]
```

Then we could use it in `\BEdita\Core\Model\Validation\UsersValidator` to setup a custom validation rule.

But I think we can live with it for now.

**Comment by stefanorosanelli** [comment]
Ok for the new config, but in this particular case we need to have a check before validation rules: at validation step password is already encrypted.
I had to use `beforeMarshal()` for that reason...

**Comment by batopa** [comment]
Uhm... validation rules (not application rules) should be applied before data is converted into entity. Do we have already hashed password?

Go with the config anyway.

**Review by batopa — APPROVED** [review]

**Review by didoda — APPROVED** [review]

**Comment by batopa** [comment]
ok I merge and open an issue to move check at data validation level.

**Pull request merged**
