### PR TITLE
Implement `/roles` API endpoint

### PR DESCRIPTION
**Pull request by fquffio**
This PR implements `/roles` and `/roles/:role_id/users` API endpoints, as of #855. It also adds `RolesUsersFixture` to `BEdita/Core` plugin.

Please, check carefully that no previously existing functionalities were broken, as some refactors were needed (mainly in routing and pagination links building).

### CODE REVIEW

**Comment by stefanorosanelli** [comment]
Seems ok using `json` Accept requests, but weird things happen using `html` Accept:
- exception `Cake\Routing\Exception\MissingRouteException` on endpoint of type `/roles/1`
- pagination links on `/roles` are like

``` json
"links": {
        "self": "http://be4.dev/roles",
        "first": "http://be4.dev/roles?autoRender=0\u0026return=1\u0026bare=1\u0026requested=1",
        "last": "http://be4.dev/roles?autoRender=0\u0026return=1\u0026bare=1\u0026requested=1\u0026page=2",
        "prev": null,
        "next": "http://be4.dev/roles?autoRender=0\u0026return=1\u0026bare=1\u0026requested=1\u0026page=2"
    },
```
- same beahavior on `/users` endpoint  using `html` Accept

**Comment by stefanorosanelli** [comment]
Should we add a unit test to track `/roles/1` like cases using `html` Accept header?

**Comment by fquffio** [comment]
Ouch! Yeah, both are issues arose after 517f9db. I'll take a look.
We might add unit tests to test the HTML display, but I think it would be quite hard to properly test such feature.

**Comment by stefanorosanelli** [comment]
Yes, testing HTML display content is not an easy task, and the HTML response is still not well defined.
But we could simply test response code for urls like `/roles/1` and `/users/1`

**Pull request merged**
